# Hello-Notes
rapping shcemes
1•I walk around like a space cadet.
2•Just wagging wars and making bets.
3•Anxiety in thi twisted up society no regrets
4•Angry lil prick building white picket fences.
5•Racist neighbors looking listening cutting hedges
6•Armageddon at hand warring everybody busting in women 
7•nuts on bitches pulling wedgies murdering braindead bitches 
8•making messes count my blessing as I rap rhyme tryna sing infringes
7•My dick in woman as it stinking inside there pussy dumb dead bread crumbed
8•Imagination got me thinking dangerous tryna except the PMS good for nothing 
9• hookers that font type front phoenicia felatio dick breath snitches
Chorus//
YOU IN LOVE WITH THE HOE AND YOU KISS THE HOE YOU IN LOVE WITH A HOOKER BRO
JULIA ROBERTS LIAL LOVE ITS AQUISTIC LOVE HARLEQUIN JARED LITO GANGSTER ROMANTIC
 WILLIAM SHAKESPEAR BIOGRAPHIES OF DOMESTICATED FOREIGN AFFAIRS OVER DRAMATIC BROKEN HEARTED 
CHEATING IN LOVE WITH SATAN 3 DAYS IN HELL PAID THE PRICE FOR LOVE BETRAYED MURDERING HEARTLESS BITCH!
I PAID FOR EVERYTHING WITH MY LIFE I DIED FOR LOVING A 2 FACED EVIL NARCASSIST! PLAYED WITH MY HEART I WAS HER  MARK 
THEY PLANNED MY MURDER TWICE AND I FORGAVE YOU BITCH THEN YOU DID IT AGAIN YOU WANTED ME DEAD MY LOVE MENT NOTHING YOU HEATHEN PIG 
SWINE DEL LA CREME CUM DUMP WITCH! 
\\ 

1•Make it first like best wicked bithes cum on there faces cause they blessed.
2•Guess I'll just flex take off my vest cause I'm like 50 cent rich n fresh .
3•Like this is how I battle wars arranging whores for agent orange 
4•Clocked work got no time to cry over whores when I have trophy bitches that love it.
5•When I eat there pussies and suck on there clit like a carnivore .
6•Sharpen up my cajun sword in battle with many men like boy George. 
7•That want to be in a boy band with sodomizers that keep tryna sleep with me knocking on my door.
8•Bunch of scary looking tranniesthat used to be men but got fake titts so when they have sex with them 

Chorus\\


 //
1•They are riding you like a horny bitch addicted to floppy bits of tummy sticks chicks with dicks 
2•As a cocks flapping up n down flopping around like floppy chop sticks just rubbing pricks. 
3•Change my sex preferences and sex position as I become a lesbian on the floor having sex with exotic bitches and Ellen degenerates 
4•Wanna be copies encrypted trojan bitch misfits of cleoatrice with big black dick pussy fits in your ass like black mass with Pope Francis again keep six
5•Taping your ass after black mass catholic church screaming no father it hurts with his balls deep in your kids ass black masses in assess tragically hip
6•Just getting fingered to death by a couple of non binary bitches who have no gender n call me a sexist just finger my asshole while having sex with a Pope bleep to blip
7• goverment censorship while cheating slut bitches turn menevont use there pushes to hypnotize men turn them blind in a pandemic hollusinate like Saddam housain babylonians 
8•in the midst of benedict'fornicating other men while praying to satan 5 minutes pregnant till I gave birth pand ssed some gas and pinched a loaf swore on a oath banging your wife with just the tip
9• Horny unholy trinity bitches love BBC and dick Same old bare back shit Barack Obama in there assess again unfaithful un true slut cunt wenches cleopatrice actresses in Egypt Useing there poison murdering Harlequin 
8• loose lips sink ships like I took a shit and played a golden nugget labyrinth with your wife in the middle of the sandwich as I compressed the bitch she was screaming while burger king and mcdicks double 2 dic 
10•dick kinder surprise bitches flip a bit like verb variables centmental silver dollar coin Memorabilia storage silica microchip platonic Sports memory meme drew Carey Cleveland Ohio sit com funny bias bad memories from narcassist cleptomanic 
11• Rod of mercury in the mind of ascleptio ascleptia clymidia dirty stink pussy disease infested rat bio hazard contagious carrier menevont trojan virus I polar anti matter ant eater termite parasite cunt trick evil bitches
